url: "https://uclit.ca" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "UC Lit" # the name of your site, e.g. ACME Corp.
sass:
  sass_dir: assets/css 

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - README.md
  - Docs/

tagline: "Welcome to the UC Lit's official website."
email: your.email@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome the the UC Lit, the oldest 
  democratically-elected student government
  in Canada
google_analytics: UA-111111111-1